### ISSUE TITLE
No Gaze Input/ Reticle in the player for Navigation. 

### ISSUE THREAD

**Issue by devesh2605** [Wef2/android-vr-player#1]
Hello,
I have tried your app, works really well but when we launch a video file and put the smartphone on the headset then there is no option if going back, playing, pausing?. I am guessing you have missed this. This problem can be solved by using the Gaze input, well there is no native implementation for this in android unlike Unity has..

**Comment by Wef2** [comment]
Hello.
Sorry for late reply. I just make this project for simple test. So the project is no longer maintained. Try some other high quality VR source code sample like Google VR.
